language: node_js
node_js:
- '7'
before_deploy:
- npm run build
- cp src/robots.txt dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: 0.2/release
env:
  global:
    secure: A3fyeIIHmLve7Z6KjrMdrQYLS33cutHw+/dUq6jQD0iZQBU+1KZZ6m4Jfvik5MJWqntJ8Ydlzb0WTC7RVmjo45Mr66Q2GFdLKQk4QQvxEHtWA0Zvr0mllLj78PI1KeJyPkNIvJDYPnb3PAvXmNP0/ApzKYn3GfIO86NyN9My8AKOEAlDhk8kdlTAm17IErtu2SAjP8kS39/mXfFiIbVgEcw7EkynYmM6aIGadopkEImd4efdjngMOVpr8Dx8vNshxcth6XDSjCH0MR7rOCtCXIZetURyY0rcKGvX7E9uzjsMARAO5qHvyQvBqrCJWE3ScAb5F2jyqizTwM/PPanxiYlje+paACMxtYnydlseeU5HAFsFI6Nbi2DeIC5t6FUWUdcKdJU0JogVJJWYObTY+HBd+IYeA6ZZVvpNbDHDZUBQTTL959ysv0ylDVSI+ONNN38VU4XI9STIKZMjQTNAxlB/6b9aUwEmsnrlIQqkoCVJA2UPq0LJ79gSw4c7XvMykiM3Sy47Qt0dNgv5HTcq+xnzD88KUcdYgQ1RKN1oor0vhIx/Q5v1rYrQKp6NPcac8kpD0kBQwB2f1P1Z2FU2uTyleShID+SK+MOoR6vUgHT1mKCa2nabQCAX+epy2UUE54RSVT9liW1il1998GgoFRwNfvgNlxiKhf83CcVQLPM=
