language: node_js
node_js:
    - "4"

before_deploy:
    - echo "start"
    - npm run build
    - echo "finished"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: 0.1/release
