# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:  
#   push:
#     branches: [ "1.7/release" ]
#   pull_request:
#     branches: [ "1.7/release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: test
